memory_limit=512M
max_execution_time=300
max_input_vars=10000
upload_max_filesize=32M
post_max_size=40M
date.timezone=Europe/Madrid
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
opcache.enable=1
opcache.memory_consumption=128
opcache.validate_timestamps=1
session.cookie_httponly=1
session.cookie_samesite=Lax
expose_php=Off
